version: "3.8"

services:
  backend:
    build: .
    container_name: cinematch-be
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}
      - MONGODB_URI=${MONGODB_URI}
      - MONGODB_DBNAME=${MONGODB_DBNAME}
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: cinematch-db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
